/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package steambay.ui;

import java.awt.Frame;
import java.awt.event.WindowEvent;

/**
 *
 * @author Daniel
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setExtendedState(this.getExtendedState() | javax.swing.JFrame.MAXIMIZED_BOTH);
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JMenuBar();
        Arquivo = new javax.swing.JMenu();
        Sair = new javax.swing.JMenuItem();
        Editar = new javax.swing.JMenu();
        Fornecedor = new javax.swing.JMenu();
        GerFornec = new javax.swing.JMenuItem();
        Jogo = new javax.swing.JMenu();
        GerJogo = new javax.swing.JMenuItem();
        Pedido = new javax.swing.JMenu();
        GerPed = new javax.swing.JMenuItem();
        GerCar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SteamBay");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Arquivo.setText("Arquivo");

        Sair.setMnemonic('S');
        Sair.setText("Sair");
        Sair.setToolTipText("Sair do programa.");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Arquivo.add(Sair);

        Menu.add(Arquivo);

        Editar.setText("Editar");
        Menu.add(Editar);

        Fornecedor.setText("Fornecedor");

        GerFornec.setMnemonic('F');
        GerFornec.setText("Gerenciar Fornecedor");
        GerFornec.setToolTipText("Tela de gerenciamento de fornecedor.");
        GerFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerFornecActionPerformed(evt);
            }
        });
        Fornecedor.add(GerFornec);

        Menu.add(Fornecedor);

        Jogo.setText("Jogo");

        GerJogo.setMnemonic('J');
        GerJogo.setText("Gerenciar Jogo");
        GerJogo.setToolTipText("Tela de gerenciamento de jogos.");
        GerJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerJogoActionPerformed(evt);
            }
        });
        Jogo.add(GerJogo);

        Menu.add(Jogo);

        Pedido.setText("Pedido");

        GerPed.setMnemonic('P');
        GerPed.setText("Gerenciar Pedido");
        GerPed.setToolTipText("Tela de gerenciamento de pedidos.");
        GerPed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerPedActionPerformed(evt);
            }
        });
        Pedido.add(GerPed);

        GerCar.setMnemonic('C');
        GerCar.setText("Gerenciar Carrinho");
        GerCar.setToolTipText("Tela de gerenciamento de carrinho de compras.");
        GerCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerCarActionPerformed(evt);
            }
        });
        Pedido.add(GerCar);

        Menu.add(Pedido);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        System.exit(-1);
    }//GEN-LAST:event_SairActionPerformed

    private void GerFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerFornecActionPerformed
        CadastrarFornecedorUI cdfui = new CadastrarFornecedorUI();
        cdfui.setVisible(true);
    }//GEN-LAST:event_GerFornecActionPerformed

    private void GerJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerJogoActionPerformed
        CadastrarProdutoUI cdpui = new CadastrarProdutoUI();
        cdpui.setVisible(true);
    }//GEN-LAST:event_GerJogoActionPerformed

    private void GerPedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerPedActionPerformed
        GerenciarPedidoUI grpeui = new GerenciarPedidoUI();
        grpeui.setVisible(true);
    }//GEN-LAST:event_GerPedActionPerformed

    private void GerCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerCarActionPerformed
        GerenciarCarrinhoUI grcaui = new GerenciarCarrinhoUI();
        grcaui.setVisible(true);
    }//GEN-LAST:event_GerCarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Arquivo;
    private javax.swing.JMenu Editar;
    private javax.swing.JMenu Fornecedor;
    private javax.swing.JMenuItem GerCar;
    private javax.swing.JMenuItem GerFornec;
    private javax.swing.JMenuItem GerJogo;
    private javax.swing.JMenuItem GerPed;
    private javax.swing.JMenu Jogo;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu Pedido;
    private javax.swing.JMenuItem Sair;
    // End of variables declaration//GEN-END:variables
}
